env:
  - CXX=g++-4.8
sudo: false
language: node_js
node_js:
  - "6"
  - "7"
before_script:
  - npm install -g gulp-cli 
  - npm install 
  - gulp tslint
  - node_modules/.bin/dts-generator --project .  --out index.d.ts
deploy:
  provider: script
  script: publish.sh
  on:
    tags: true
    all_branches: false
    condition: "$TRAVIS_TAG =~ ^([0-9]+).([0-9]+).([0-9]+).*$"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8