env:
  - CXX=g++-4.8
sudo: false
language: node_js
node_js:
  - "6"
  - "7"
before_script:
  - npm install -g gulp-cli 
  - npm install 
  - sed '3168d'  node_modules/typescript/lib/typescript.js >>  node_modules/typescript/lib/typescript_new.js
  - cp  node_modules/typescript/lib/typescript_new.js  node_modules/typescript/lib/typescript.js
  - gulp ts
deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_AUTH
  on:
    tags: true
    all_branches: false
    condition: "$TRAVIS_TAG =~ ^([0-9]+).([0-9]+).([0-9]+).*$"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
