sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
before_script:
  - npm install 
  - node_modules/.bin/dts-generator --project .  --out index.d.ts
deploy:
  provider: script
  script: publish.sh
  on:
    tags: true
    all_branches: false
    condition: "$TRAVIS_TAG =~ ^([0-9]+).([0-9]+).([0-9]+).*$"